[mypy]
disallow_untyped_defs = False

[mypy-numpy.*]
ignore_missing_imports = True

[mypy-affine.*]
ignore_missing_imports = True
[mypy-celery]
ignore_missing_imports = True
[mypy-vcr]
ignore_missing_imports = True
[mypy-shapely.*]
ignore_missing_imports = True
[mypy-rasterio.*]
ignore_missing_imports = True
[mypy-cv2]
ignore_missing_imports = True
